# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(853, 682)
        MainWindow.setMinimumSize(QtCore.QSize(853, 682))
        MainWindow.setMaximumSize(QtCore.QSize(853, 682))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(366, 9, 457, 428))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_54.setObjectName("label_54")
        self.gridLayout_2.addWidget(self.label_54, 14, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 11, 0, 1, 3)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 8, 0, 1, 1)
        self.lineEdit_axial_force = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_axial_force.setEnabled(True)
        self.lineEdit_axial_force.setObjectName("lineEdit_axial_force")
        self.gridLayout_2.addWidget(self.lineEdit_axial_force, 9, 1, 1, 1)
        self.lineEdit_shear_force = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_shear_force.setEnabled(True)
        self.lineEdit_shear_force.setObjectName("lineEdit_shear_force")
        self.gridLayout_2.addWidget(self.lineEdit_shear_force, 8, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 8, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 9, 0, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_55.setObjectName("label_55")
        self.gridLayout_2.addWidget(self.label_55, 14, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 9, 2, 1, 1)
        self.lineEdit_ratio_bm = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_ratio_bm.setEnabled(False)
        self.lineEdit_ratio_bm.setObjectName("lineEdit_ratio_bm")
        self.gridLayout_2.addWidget(self.lineEdit_ratio_bm, 15, 1, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_57.setObjectName("label_57")
        self.gridLayout_2.addWidget(self.label_57, 16, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_53.setObjectName("label_53")
        self.gridLayout_2.addWidget(self.label_53, 13, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_49.setObjectName("label_49")
        self.gridLayout_2.addWidget(self.label_49, 12, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_51.setObjectName("label_51")
        self.gridLayout_2.addWidget(self.label_51, 13, 0, 1, 1)
        self.lineEdit_second_moment_cover = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_second_moment_cover.setEnabled(False)
        self.lineEdit_second_moment_cover.setObjectName("lineEdit_second_moment_cover")
        self.gridLayout_2.addWidget(self.lineEdit_second_moment_cover, 14, 1, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_50.setObjectName("label_50")
        self.gridLayout_2.addWidget(self.label_50, 16, 0, 1, 1)
        self.lineEdit_second_web_moment = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_second_web_moment.setEnabled(False)
        self.lineEdit_second_web_moment.setObjectName("lineEdit_second_web_moment")
        self.gridLayout_2.addWidget(self.lineEdit_second_web_moment, 12, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_56.setObjectName("label_56")
        self.gridLayout_2.addWidget(self.label_56, 15, 0, 1, 1)
        self.lineEdit_second_moment_single_pfc = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_second_moment_single_pfc.setEnabled(False)
        self.lineEdit_second_moment_single_pfc.setObjectName("lineEdit_second_moment_single_pfc")
        self.gridLayout_2.addWidget(self.lineEdit_second_moment_single_pfc, 13, 1, 1, 1)
        self.lineEdit_bending_moment_cover = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_bending_moment_cover.setEnabled(False)
        self.lineEdit_bending_moment_cover.setObjectName("lineEdit_bending_moment_cover")
        self.gridLayout_2.addWidget(self.lineEdit_bending_moment_cover, 16, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.gridLayout_2.addWidget(self.label_52, 12, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_2.addWidget(self.label_37, 5, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_2.addWidget(self.label_41, 2, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 3, 2, 1, 1)
        self.lineEdit_plate_ultimate_strength = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_plate_ultimate_strength.setEnabled(False)
        self.lineEdit_plate_ultimate_strength.setObjectName("lineEdit_plate_ultimate_strength")
        self.gridLayout_2.addWidget(self.lineEdit_plate_ultimate_strength, 6, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 4, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_2.addWidget(self.label_38, 6, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 5, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 4, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_2.addWidget(self.label_40, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 3, 0, 1, 1)
        self.combo_steel_grade_plate = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.combo_steel_grade_plate.setObjectName("combo_steel_grade_plate")
        self.combo_steel_grade_plate.addItem("")
        self.combo_steel_grade_plate.addItem("")
        self.gridLayout_2.addWidget(self.combo_steel_grade_plate, 1, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_2.addWidget(self.label_39, 2, 0, 1, 1)
        self.combo_steel_thickness_plate = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.combo_steel_thickness_plate.setObjectName("combo_steel_thickness_plate")
        self.combo_steel_thickness_plate.addItem("")
        self.combo_steel_thickness_plate.addItem("")
        self.combo_steel_thickness_plate.addItem("")
        self.gridLayout_2.addWidget(self.combo_steel_thickness_plate, 2, 1, 1, 1)
        self.lineEdit_plate_yield_strength = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_plate_yield_strength.setEnabled(False)
        self.lineEdit_plate_yield_strength.setObjectName("lineEdit_plate_yield_strength")
        self.gridLayout_2.addWidget(self.lineEdit_plate_yield_strength, 5, 1, 1, 1)
        self.lineEdit_plate_depth = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_plate_depth.setEnabled(True)
        self.lineEdit_plate_depth.setObjectName("lineEdit_plate_depth")
        self.gridLayout_2.addWidget(self.lineEdit_plate_depth, 4, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 6, 0, 1, 1)
        self.lineEdit_plate_thickness = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_plate_thickness.setEnabled(True)
        self.lineEdit_plate_thickness.setObjectName("lineEdit_plate_thickness")
        self.gridLayout_2.addWidget(self.lineEdit_plate_thickness, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 7, 0, 1, 3)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 0, 0, 1, 3)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 351, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 10, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 10, 2, 1, 1)
        self.lineEdit_web_height = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_web_height.setEnabled(False)
        self.lineEdit_web_height.setObjectName("lineEdit_web_height")
        self.gridLayout.addWidget(self.lineEdit_web_height, 9, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 9, 0, 1, 1)
        self.depth_flange_fillets = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.depth_flange_fillets.setEnabled(False)
        self.depth_flange_fillets.setObjectName("depth_flange_fillets")
        self.gridLayout.addWidget(self.depth_flange_fillets, 10, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 9, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLineWidth(1)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.lineEdit_web_thickness = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_web_thickness.setEnabled(False)
        self.lineEdit_web_thickness.setObjectName("lineEdit_web_thickness")
        self.gridLayout.addWidget(self.lineEdit_web_thickness, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 17, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 16, 0, 1, 1)
        self.beam_yield_strength = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.beam_yield_strength.setEnabled(False)
        self.beam_yield_strength.setObjectName("beam_yield_strength")
        self.gridLayout.addWidget(self.beam_yield_strength, 16, 1, 1, 1)
        self.combo_steel_thickness_beam = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_steel_thickness_beam.setObjectName("combo_steel_thickness_beam")
        self.combo_steel_thickness_beam.addItem("")
        self.combo_steel_thickness_beam.addItem("")
        self.combo_steel_thickness_beam.addItem("")
        self.gridLayout.addWidget(self.combo_steel_thickness_beam, 13, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 17, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 13, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 13, 2, 1, 1)
        self.lineEdit_beam_ultimate_strength = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_beam_ultimate_strength.setEnabled(False)
        self.lineEdit_beam_ultimate_strength.setObjectName("lineEdit_beam_ultimate_strength")
        self.gridLayout.addWidget(self.lineEdit_beam_ultimate_strength, 17, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 8, 0, 1, 3)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 16, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 12, 0, 1, 1)
        self.combo_steal_grade_beam = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_steal_grade_beam.setObjectName("combo_steal_grade_beam")
        self.combo_steal_grade_beam.addItem("")
        self.combo_steal_grade_beam.addItem("")
        self.gridLayout.addWidget(self.combo_steal_grade_beam, 12, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 7, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 2, 1, 1)
        self.root_radius = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.root_radius.setEnabled(False)
        self.root_radius.setObjectName("root_radius")
        self.gridLayout.addWidget(self.root_radius, 6, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 2, 1, 1)
        self.flange_thickness = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.flange_thickness.setEnabled(False)
        self.flange_thickness.setObjectName("flange_thickness")
        self.gridLayout.addWidget(self.flange_thickness, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        self.beam_depth = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.beam_depth.setEnabled(False)
        self.beam_depth.setObjectName("beam_depth")
        self.gridLayout.addWidget(self.beam_depth, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 2, 1, 1)
        self.second_moment_area = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.second_moment_area.setEnabled(False)
        self.second_moment_area.setObjectName("second_moment_area")
        self.gridLayout.addWidget(self.second_moment_area, 7, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.combo_beam_size = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_beam_size.setObjectName("combo_beam_size")
        self.gridLayout.addWidget(self.combo_beam_size, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 811, 191))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_bolt_class = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_bolt_class.setObjectName("comboBox_bolt_class")
        self.comboBox_bolt_class.addItem("")
        self.comboBox_bolt_class.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_bolt_class, 2, 1, 1, 1)
        self.lineEdit_bolt_diameter = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_bolt_diameter.setEnabled(False)
        self.lineEdit_bolt_diameter.setMaxLength(20)
        self.lineEdit_bolt_diameter.setObjectName("lineEdit_bolt_diameter")
        self.gridLayout_4.addWidget(self.lineEdit_bolt_diameter, 4, 1, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_117.setObjectName("label_117")
        self.gridLayout_4.addWidget(self.label_117, 5, 2, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_115.setObjectName("label_115")
        self.gridLayout_4.addWidget(self.label_115, 3, 2, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_116.setObjectName("label_116")
        self.gridLayout_4.addWidget(self.label_116, 4, 2, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_113.setObjectName("label_113")
        self.gridLayout_4.addWidget(self.label_113, 3, 0, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_114.setObjectName("label_114")
        self.gridLayout_4.addWidget(self.label_114, 5, 0, 1, 1)
        self.comboBox_bolt_shank_diameter = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_bolt_shank_diameter.setObjectName("comboBox_bolt_shank_diameter")
        self.comboBox_bolt_shank_diameter.addItem("")
        self.comboBox_bolt_shank_diameter.addItem("")
        self.comboBox_bolt_shank_diameter.addItem("")
        self.comboBox_bolt_shank_diameter.addItem("")
        self.comboBox_bolt_shank_diameter.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_bolt_shank_diameter, 3, 1, 1, 1)
        self.lineEdit_bolt_shear = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_bolt_shear.setEnabled(False)
        self.lineEdit_bolt_shear.setMaxLength(20)
        self.lineEdit_bolt_shear.setObjectName("lineEdit_bolt_shear")
        self.gridLayout_4.addWidget(self.lineEdit_bolt_shear, 5, 1, 1, 1)
        self.label_118 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_118.setObjectName("label_118")
        self.gridLayout_4.addWidget(self.label_118, 2, 0, 1, 1)
        self.label_120 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_120.setObjectName("label_120")
        self.gridLayout_4.addWidget(self.label_120, 4, 0, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_119.setFont(font)
        self.label_119.setObjectName("label_119")
        self.gridLayout_4.addWidget(self.label_119, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 6, 0, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_4)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_121 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_121.setFont(font)
        self.label_121.setObjectName("label_121")
        self.gridLayout_11.addWidget(self.label_121, 4, 0, 1, 1)
        self.label_124 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_124.setObjectName("label_124")
        self.gridLayout_11.addWidget(self.label_124, 1, 2, 1, 1)
        self.label_123 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_123.setFont(font)
        self.label_123.setObjectName("label_123")
        self.gridLayout_11.addWidget(self.label_123, 1, 0, 1, 1)
        self.lineEdit_bolts_mratio = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_bolts_mratio.setEnabled(False)
        self.lineEdit_bolts_mratio.setMaxLength(20)
        self.lineEdit_bolts_mratio.setFrame(True)
        self.lineEdit_bolts_mratio.setClearButtonEnabled(False)
        self.lineEdit_bolts_mratio.setObjectName("lineEdit_bolts_mratio")
        self.gridLayout_11.addWidget(self.lineEdit_bolts_mratio, 1, 1, 1, 1)
        self.lineEdit_madd = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_madd.setEnabled(False)
        self.lineEdit_madd.setMaxLength(20)
        self.lineEdit_madd.setFrame(True)
        self.lineEdit_madd.setClearButtonEnabled(False)
        self.lineEdit_madd.setObjectName("lineEdit_madd")
        self.gridLayout_11.addWidget(self.lineEdit_madd, 4, 1, 1, 1)
        self.label_127 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_127.setObjectName("label_127")
        self.gridLayout_11.addWidget(self.label_127, 4, 2, 1, 1)
        self.label_128 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_128.setFont(font)
        self.label_128.setObjectName("label_128")
        self.gridLayout_11.addWidget(self.label_128, 2, 0, 1, 1)
        self.lineEdit_f_ved = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_f_ved.setEnabled(False)
        self.lineEdit_f_ved.setMaxLength(20)
        self.lineEdit_f_ved.setFrame(True)
        self.lineEdit_f_ved.setClearButtonEnabled(False)
        self.lineEdit_f_ved.setObjectName("lineEdit_f_ved")
        self.gridLayout_11.addWidget(self.lineEdit_f_ved, 2, 1, 1, 1)
        self.label_132 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_132.setObjectName("label_132")
        self.gridLayout_11.addWidget(self.label_132, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem2, 5, 0, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.gridLayout_11)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(410, 10, 411, 219))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_144 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_144.setFont(font)
        self.label_144.setObjectName("label_144")
        self.gridLayout_5.addWidget(self.label_144, 3, 0, 1, 1)
        self.label_143 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_143.setObjectName("label_143")
        self.gridLayout_5.addWidget(self.label_143, 3, 2, 1, 1)
        self.lineEdit_f_hor = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_f_hor.setEnabled(False)
        self.lineEdit_f_hor.setMaxLength(3)
        self.lineEdit_f_hor.setFrame(True)
        self.lineEdit_f_hor.setClearButtonEnabled(False)
        self.lineEdit_f_hor.setObjectName("lineEdit_f_hor")
        self.gridLayout_5.addWidget(self.lineEdit_f_hor, 2, 1, 1, 1)
        self.lineEdit_i_bolt = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_i_bolt.setEnabled(False)
        self.lineEdit_i_bolt.setMaxLength(10)
        self.lineEdit_i_bolt.setFrame(True)
        self.lineEdit_i_bolt.setClearButtonEnabled(False)
        self.lineEdit_i_bolt.setObjectName("lineEdit_i_bolt")
        self.gridLayout_5.addWidget(self.lineEdit_i_bolt, 0, 1, 1, 1)
        self.label_146 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_146.setFont(font)
        self.label_146.setObjectName("label_146")
        self.gridLayout_5.addWidget(self.label_146, 0, 0, 1, 1)
        self.label_140 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_140.setObjectName("label_140")
        self.gridLayout_5.addWidget(self.label_140, 4, 2, 1, 1)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_62.setEnabled(False)
        self.lineEdit_62.setMaxLength(3)
        self.lineEdit_62.setFrame(True)
        self.lineEdit_62.setClearButtonEnabled(False)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout_5.addWidget(self.lineEdit_62, 4, 1, 1, 1)
        self.label_148 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_148.setFont(font)
        self.label_148.setObjectName("label_148")
        self.gridLayout_5.addWidget(self.label_148, 4, 0, 1, 1)
        self.lineEdit_f_ver = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_f_ver.setEnabled(False)
        self.lineEdit_f_ver.setMaxLength(3)
        self.lineEdit_f_ver.setFrame(True)
        self.lineEdit_f_ver.setClearButtonEnabled(False)
        self.lineEdit_f_ver.setObjectName("lineEdit_f_ver")
        self.gridLayout_5.addWidget(self.lineEdit_f_ver, 3, 1, 1, 1)
        self.label_145 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_145.setObjectName("label_145")
        self.gridLayout_5.addWidget(self.label_145, 0, 2, 1, 1)
        self.label_147 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_147.setObjectName("label_147")
        self.gridLayout_5.addWidget(self.label_147, 2, 2, 1, 1)
        self.label_141 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_141.setFont(font)
        self.label_141.setObjectName("label_141")
        self.gridLayout_5.addWidget(self.label_141, 2, 0, 1, 1)
        self.label_Fr_Fvrd = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Fr_Fvrd.setFont(font)
        self.label_Fr_Fvrd.setObjectName("label_Fr_Fvrd")
        self.gridLayout_5.addWidget(self.label_Fr_Fvrd, 5, 0, 1, 1)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_63.setEnabled(False)
        self.lineEdit_63.setMaxLength(3)
        self.lineEdit_63.setFrame(True)
        self.lineEdit_63.setClearButtonEnabled(False)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.gridLayout_5.addWidget(self.lineEdit_63, 5, 1, 1, 1)
        self.label_ibolt = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_ibolt.setObjectName("label_ibolt")
        self.gridLayout_5.addWidget(self.label_ibolt, 1, 0, 1, 3)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(250, 120, 111, 86))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.spinBox_columns = QtWidgets.QSpinBox(self.gridLayoutWidget_9)
        self.spinBox_columns.setMinimum(2)
        self.spinBox_columns.setMaximum(10)
        self.spinBox_columns.setObjectName("spinBox_columns")
        self.gridLayout_12.addWidget(self.spinBox_columns, 0, 1, 1, 1)
        self.spinBox_rows = QtWidgets.QSpinBox(self.gridLayoutWidget_9)
        self.spinBox_rows.setMinimum(2)
        self.spinBox_rows.setMaximum(10)
        self.spinBox_rows.setObjectName("spinBox_rows")
        self.gridLayout_12.addWidget(self.spinBox_rows, 1, 1, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_88.setFont(font)
        self.label_88.setObjectName("label_88")
        self.gridLayout_12.addWidget(self.label_88, 0, 0, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_89.setFont(font)
        self.label_89.setObjectName("label_89")
        self.gridLayout_12.addWidget(self.label_89, 1, 0, 1, 1)
        self.label_93 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.gridLayout_12.addWidget(self.label_93, 2, 0, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.lineEdit_39.setEnabled(False)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_12.addWidget(self.lineEdit_39, 2, 1, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 391, 111))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_90 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_90.setObjectName("label_90")
        self.gridLayout_9.addWidget(self.label_90, 1, 0, 1, 1)
        self.label_91 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_91.setFont(font)
        self.label_91.setObjectName("label_91")
        self.gridLayout_9.addWidget(self.label_91, 1, 1, 1, 1)
        self.label_94 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_94.setFont(font)
        self.label_94.setObjectName("label_94")
        self.gridLayout_9.addWidget(self.label_94, 2, 0, 1, 1)
        self.lineEdit_fb = QtWidgets.QLineEdit(self.gridLayoutWidget_7)
        self.lineEdit_fb.setEnabled(False)
        self.lineEdit_fb.setObjectName("lineEdit_fb")
        self.gridLayout_9.addWidget(self.lineEdit_fb, 2, 1, 1, 1)
        self.label_95 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_95.setFont(font)
        self.label_95.setObjectName("label_95")
        self.gridLayout_9.addWidget(self.label_95, 2, 2, 1, 1)
        self.label_96 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.label_96.setObjectName("label_96")
        self.gridLayout_9.addWidget(self.label_96, 0, 0, 1, 3)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(10, 120, 233, 138))
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_97 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_97.setFont(font)
        self.label_97.setObjectName("label_97")
        self.gridLayout_13.addWidget(self.label_97, 3, 4, 1, 1)
        self.label_98 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_98.setFont(font)
        self.label_98.setObjectName("label_98")
        self.gridLayout_13.addWidget(self.label_98, 4, 2, 1, 1)
        self.label_99 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")
        self.gridLayout_13.addWidget(self.label_99, 2, 4, 1, 1)
        self.label_100 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.gridLayout_13.addWidget(self.label_100, 1, 4, 1, 1)
        self.lineEdit_p2 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_p2.setEnabled(True)
        self.lineEdit_p2.setMaxLength(3)
        self.lineEdit_p2.setFrame(True)
        self.lineEdit_p2.setClearButtonEnabled(False)
        self.lineEdit_p2.setObjectName("lineEdit_p2")
        self.gridLayout_13.addWidget(self.lineEdit_p2, 3, 3, 1, 1)
        self.lineEdit_e2 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_e2.setEnabled(True)
        self.lineEdit_e2.setMaxLength(3)
        self.lineEdit_e2.setFrame(True)
        self.lineEdit_e2.setClearButtonEnabled(False)
        self.lineEdit_e2.setObjectName("lineEdit_e2")
        self.gridLayout_13.addWidget(self.lineEdit_e2, 2, 3, 1, 1)
        self.lineEdit_p0 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_p0.setEnabled(True)
        self.lineEdit_p0.setMaxLength(3)
        self.lineEdit_p0.setFrame(True)
        self.lineEdit_p0.setClearButtonEnabled(False)
        self.lineEdit_p0.setObjectName("lineEdit_p0")
        self.gridLayout_13.addWidget(self.lineEdit_p0, 4, 3, 1, 1)
        self.lineEdit_p1 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_p1.setEnabled(True)
        self.lineEdit_p1.setMaxLength(3)
        self.lineEdit_p1.setFrame(True)
        self.lineEdit_p1.setClearButtonEnabled(False)
        self.lineEdit_p1.setObjectName("lineEdit_p1")
        self.gridLayout_13.addWidget(self.lineEdit_p1, 1, 3, 1, 1)
        self.label_101 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_101.setFont(font)
        self.label_101.setObjectName("label_101")
        self.gridLayout_13.addWidget(self.label_101, 2, 2, 1, 1)
        self.label_102 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_102.setFont(font)
        self.label_102.setObjectName("label_102")
        self.gridLayout_13.addWidget(self.label_102, 3, 2, 1, 1)
        self.label_103 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_103.setFont(font)
        self.label_103.setObjectName("label_103")
        self.gridLayout_13.addWidget(self.label_103, 4, 4, 1, 1)
        self.label_104 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_104.setFont(font)
        self.label_104.setObjectName("label_104")
        self.gridLayout_13.addWidget(self.label_104, 1, 2, 1, 1)
        self.lineEdit_e1 = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        self.lineEdit_e1.setEnabled(True)
        self.lineEdit_e1.setMaxLength(3)
        self.lineEdit_e1.setFrame(True)
        self.lineEdit_e1.setClearButtonEnabled(False)
        self.lineEdit_e1.setObjectName("lineEdit_e1")
        self.gridLayout_13.addWidget(self.lineEdit_e1, 0, 3, 1, 1)
        self.label_105 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_105.setFont(font)
        self.label_105.setObjectName("label_105")
        self.gridLayout_13.addWidget(self.label_105, 0, 4, 1, 1)
        self.label_106 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_106.setFont(font)
        self.label_106.setObjectName("label_106")
        self.gridLayout_13.addWidget(self.label_106, 0, 2, 1, 1)
        self.label_107 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_107.setFont(font)
        self.label_107.setObjectName("label_107")
        self.gridLayout_13.addWidget(self.label_107, 3, 1, 1, 1)
        self.label_149 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_149.setFont(font)
        self.label_149.setObjectName("label_149")
        self.gridLayout_13.addWidget(self.label_149, 0, 1, 1, 1)
        self.label_150 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_150.setFont(font)
        self.label_150.setObjectName("label_150")
        self.gridLayout_13.addWidget(self.label_150, 1, 1, 1, 1)
        self.label_151 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_151.setFont(font)
        self.label_151.setObjectName("label_151")
        self.gridLayout_13.addWidget(self.label_151, 2, 1, 1, 1)
        self.label_152 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_152.setFont(font)
        self.label_152.setObjectName("label_152")
        self.gridLayout_13.addWidget(self.label_152, 4, 1, 1, 1)
        self.label_diagram = QtWidgets.QLabel(self.tab_4)
        self.label_diagram.setGeometry(QtCore.QRect(10, 260, 741, 301))
        self.label_diagram.setText("")
        self.label_diagram.setPixmap(QtGui.QPixmap("media/4x3.jpeg"))
        self.label_diagram.setScaledContents(True)
        self.label_diagram.setObjectName("label_diagram")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 120, 341, 138))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_112 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_112.setFont(font)
        self.label_112.setObjectName("label_112")
        self.gridLayout_8.addWidget(self.label_112, 2, 0, 1, 1)
        self.label_222 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_222.setFont(font)
        self.label_222.setObjectName("label_222")
        self.gridLayout_8.addWidget(self.label_222, 4, 0, 1, 1)
        self.label_110 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_110.setObjectName("label_110")
        self.gridLayout_8.addWidget(self.label_110, 1, 2, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_109.setFont(font)
        self.label_109.setObjectName("label_109")
        self.gridLayout_8.addWidget(self.label_109, 1, 0, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_47.setEnabled(False)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_8.addWidget(self.lineEdit_47, 1, 1, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_111.setFont(font)
        self.label_111.setObjectName("label_111")
        self.gridLayout_8.addWidget(self.label_111, 3, 0, 1, 1)
        self.lineEdit_89 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_89.setEnabled(False)
        self.lineEdit_89.setObjectName("lineEdit_89")
        self.gridLayout_8.addWidget(self.lineEdit_89, 4, 1, 1, 1)
        self.lineEdit_90 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_90.setEnabled(False)
        self.lineEdit_90.setObjectName("lineEdit_90")
        self.gridLayout_8.addWidget(self.lineEdit_90, 3, 1, 1, 1)
        self.lineEdit_91 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_91.setEnabled(True)
        self.lineEdit_91.setObjectName("lineEdit_91")
        self.gridLayout_8.addWidget(self.lineEdit_91, 2, 1, 1, 1)
        self.label_223 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_223.setObjectName("label_223")
        self.gridLayout_8.addWidget(self.label_223, 3, 2, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_108.setFont(font)
        self.label_108.setObjectName("label_108")
        self.gridLayout_8.addWidget(self.label_108, 0, 0, 1, 3)
        self.gridLayoutWidget_17 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_17.setGeometry(QtCore.QRect(10, 10, 458, 96))
        self.gridLayoutWidget_17.setObjectName("gridLayoutWidget_17")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gridLayoutWidget_17)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_228 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_228.setObjectName("label_228")
        self.gridLayout_19.addWidget(self.label_228, 3, 0, 1, 1)
        self.label_227 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_227.setObjectName("label_227")
        self.gridLayout_19.addWidget(self.label_227, 3, 2, 1, 1)
        self.lineEdit_93 = QtWidgets.QLineEdit(self.gridLayoutWidget_17)
        self.lineEdit_93.setEnabled(False)
        self.lineEdit_93.setObjectName("lineEdit_93")
        self.gridLayout_19.addWidget(self.lineEdit_93, 3, 1, 1, 1)
        self.lineEdit_92 = QtWidgets.QLineEdit(self.gridLayoutWidget_17)
        self.lineEdit_92.setEnabled(False)
        self.lineEdit_92.setObjectName("lineEdit_92")
        self.gridLayout_19.addWidget(self.lineEdit_92, 2, 1, 1, 1)
        self.label_224 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_224.setFont(font)
        self.label_224.setObjectName("label_224")
        self.gridLayout_19.addWidget(self.label_224, 1, 0, 1, 1)
        self.label_225 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_225.setObjectName("label_225")
        self.gridLayout_19.addWidget(self.label_225, 2, 0, 1, 1)
        self.label_226 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_226.setObjectName("label_226")
        self.gridLayout_19.addWidget(self.label_226, 2, 2, 1, 1)
        self.label_229 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_229.setObjectName("label_229")
        self.gridLayout_19.addWidget(self.label_229, 4, 0, 1, 1)
        self.lineEdit_94 = QtWidgets.QLineEdit(self.gridLayoutWidget_17)
        self.lineEdit_94.setEnabled(False)
        self.lineEdit_94.setObjectName("lineEdit_94")
        self.gridLayout_19.addWidget(self.lineEdit_94, 4, 1, 1, 1)
        self.label_230 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_230.setObjectName("label_230")
        self.gridLayout_19.addWidget(self.label_230, 4, 2, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.pushButton_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.verticalLayout.addWidget(self.pushButton_calculate)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 853, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Second moment of cover plate I</span><span style=\" font-size:10pt; vertical-align:sub;\">p </span><span style=\" font-size:10pt;\">= (t</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt;\">*h</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt; vertical-align:super;\">3</span><span style=\" font-size:10pt;\">) / 12 =</span></p></body></html>"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Value of moment transferred to splice cover plate</span></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Design Shear Force V</span><span style=\" font-size:10pt; vertical-align:sub;\">ed</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">kN</span></p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Design Bending Force M</span><span style=\" font-size:10pt; vertical-align:sub;\">ed</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">cm</span><span style=\" font-size:10pt; vertical-align:super;\">4</span></p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">kN*m</span></p></body></html>"))
        self.label_57.setText(_translate("MainWindow", "<html><head/><body><p>m*kN</p></body></html>"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">cm</span><span style=\" font-size:10pt; vertical-align:super;\">4</span></p></body></html>"))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Second moment of web I</span><span style=\" font-size:10pt; vertical-align:sub;\">web</span><span style=\" font-size:10pt;\">= (t</span><span style=\" font-size:10pt; vertical-align:sub;\">w</span><span style=\" font-size:10pt;\">h</span><span style=\" font-size:10pt; vertical-align:sub;\">w</span><span style=\" font-size:10pt; vertical-align:super;\">3</span><span style=\" font-size:10pt;\">) / 12=</span></p></body></html>"))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Second moment of single PFC I</span><span style=\" font-size:10pt; vertical-align:sub;\">xx</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Bending moment carried by cover plate<br/>M</span><span style=\" font-size:10pt; vertical-align:sub;\">ratio</span><span style=\" font-size:10pt;\"> = M</span><span style=\" font-size:10pt; vertical-align:sub;\">ed</span><span style=\" font-size:10pt;\"> * Ratio</span><span style=\" font-size:10pt; vertical-align:sub;\">BM</span><span style=\" font-size:10pt;\"> = </span></p></body></html>"))
        self.label_56.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Ratio of moment carried by cover plate<br/>Ratio</span><span style=\" font-size:10pt; vertical-align:sub;\">BM</span><span style=\" font-size:10pt;\">= I</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt;\">/I</span><span style=\" font-size:10pt; vertical-align:sub;\">xx </span></p></body></html>"))
        self.label_52.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">cm</span><span style=\" font-size:10pt; vertical-align:super;\">4</span></p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "N/mm^2"))
        self.label_41.setText(_translate("MainWindow", "mm"))
        self.label_31.setText(_translate("MainWindow", "mm"))
        self.label_30.setText(_translate("MainWindow", "mm"))
        self.label_38.setText(_translate("MainWindow", "N/mm^2"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Yield Strength f</span><span style=\" font-size:10pt; vertical-align:sub;\">yp</span><span style=\" font-size:10pt;\"> =</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "Cover Plate Depth hp="))
        self.label_40.setText(_translate("MainWindow", "Steel Grade"))
        self.label_28.setText(_translate("MainWindow", "Cover Plate Thickness tp ="))
        self.combo_steel_grade_plate.setItemText(0, _translate("MainWindow", "S275"))
        self.combo_steel_grade_plate.setItemText(1, _translate("MainWindow", "S355"))
        self.label_39.setText(_translate("MainWindow", "Steel Thickness <= (mm)"))
        self.combo_steel_thickness_plate.setItemText(0, _translate("MainWindow", "16"))
        self.combo_steel_thickness_plate.setItemText(1, _translate("MainWindow", "40"))
        self.combo_steel_thickness_plate.setItemText(2, _translate("MainWindow", "63"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Ultimate Strength f</span><span style=\" font-size:10pt; vertical-align:sub;\">up</span><span style=\" font-size:10pt;\"> =</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">APPLIED DESIGN LOADS (ULS)</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Cover Plate Geometry</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Depth between flange fillets<br/>d</span><span style=\" font-size:10pt; vertical-align:sub;\">b</span><span style=\" font-size:10pt;\"> = h -2(t</span><span style=\" font-size:10pt; vertical-align:sub;\">f</span><span style=\" font-size:10pt;\">+r)=</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "mm"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Web height <br/>h</span><span style=\" font-size:10pt; vertical-align:sub;\">w</span><span style=\" font-size:10pt;\">=h -2t</span><span style=\" font-size:10pt; vertical-align:sub;\">f</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "mm"))
        self.label_9.setText(_translate("MainWindow", "Beam Geometry "))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Ultimate Strength f</span><span style=\" font-size:10pt; vertical-align:sub;\">u</span><span style=\" font-size:10pt;\"> =</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Web Thickness <span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">w</span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Yield Strength f</span><span style=\" font-size:10pt; vertical-align:sub;\">y</span><span style=\" font-size:10pt;\"> =</span></p></body></html>"))
        self.combo_steel_thickness_beam.setItemText(0, _translate("MainWindow", "16"))
        self.combo_steel_thickness_beam.setItemText(1, _translate("MainWindow", "40"))
        self.combo_steel_thickness_beam.setItemText(2, _translate("MainWindow", "63"))
        self.label_36.setText(_translate("MainWindow", "N/mm^2"))
        self.label_33.setText(_translate("MainWindow", "Steel Thickness <= (mm)"))
        self.label_34.setText(_translate("MainWindow", "mm"))
        self.label_35.setText(_translate("MainWindow", "N/mm^2"))
        self.label_32.setText(_translate("MainWindow", "Steel Grade"))
        self.combo_steal_grade_beam.setItemText(0, _translate("MainWindow", "S275"))
        self.combo_steal_grade_beam.setItemText(1, _translate("MainWindow", "S355"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Second moment of area I<span style=\" vertical-align:sub;\">xx</span>=</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "mm"))
        self.label_16.setText(_translate("MainWindow", "mm"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Flange Thickness <span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">f</span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "mm"))
        self.label_13.setText(_translate("MainWindow", "mm"))
        self.label_15.setText(_translate("MainWindow", "Root radius r="))
        self.label_11.setText(_translate("MainWindow", "mm"))
        self.label_18.setText(_translate("MainWindow", "Beam Size:"))
        self.label_10.setText(_translate("MainWindow", "Beam depth h="))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Beam Geometry and Cover Plate"))
        self.comboBox_bolt_class.setItemText(0, _translate("MainWindow", "8.8"))
        self.comboBox_bolt_class.setItemText(1, _translate("MainWindow", "4.6"))
        self.label_117.setText(_translate("MainWindow", "kN"))
        self.label_115.setText(_translate("MainWindow", "mm"))
        self.label_116.setText(_translate("MainWindow", "mm"))
        self.label_113.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Bolt shank diameter d=</span></p></body></html>"))
        self.label_114.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Single Shear force resistance (ULS) F</span><span style=\" font-size:10pt; vertical-align:sub;\">vrd</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.comboBox_bolt_shank_diameter.setItemText(0, _translate("MainWindow", "12"))
        self.comboBox_bolt_shank_diameter.setItemText(1, _translate("MainWindow", "16"))
        self.comboBox_bolt_shank_diameter.setItemText(2, _translate("MainWindow", "20"))
        self.comboBox_bolt_shank_diameter.setItemText(3, _translate("MainWindow", "24"))
        self.comboBox_bolt_shank_diameter.setItemText(4, _translate("MainWindow", "30"))
        self.label_118.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Class</span></p></body></html>"))
        self.label_120.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Hole opening diameter d</span><span style=\" font-size:10pt; vertical-align:sub;\">o</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_119.setText(_translate("MainWindow", "Bolts"))
        self.label_4.setText(_translate("MainWindow", "Bolt forces at ULS"))
        self.label_121.setText(_translate("MainWindow", "<html><head/><body><p>M<span style=\" vertical-align:sub;\">add</span>=V<span style=\" vertical-align:sub;\">ed</span>*<span style=\" vertical-align:sub;\"/>(p0+ [ p1*(col -1) ] / 2)</p></body></html>"))
        self.label_124.setText(_translate("MainWindow", "kN*m"))
        self.label_123.setText(_translate("MainWindow", "<html><head/><body><p>M<span style=\" vertical-align:sub;\">ratio</span>=M<span style=\" vertical-align:sub;\">ed</span> * Ratio<span style=\" vertical-align:sub;\">BM =</span></p></body></html>"))
        self.label_127.setText(_translate("MainWindow", "kN*m"))
        self.label_128.setText(_translate("MainWindow", "<html><head/><body><p>Force per bolt due to vertical shear <br/>F<span style=\" vertical-align:sub;\">Ved</span>= V<span style=\" vertical-align:sub;\">ed </span>/ n</p></body></html>"))
        self.label_132.setText(_translate("MainWindow", "kN"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Bolts and Forces"))
        self.label_144.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">F</span><span style=\" font-weight:600; vertical-align:sub;\">ver </span><span style=\" font-weight:600;\">=</span>The Vertical component of the force<br/>on each top and bottom bolt</p></body></html>"))
        self.label_143.setText(_translate("MainWindow", "kN"))
        self.label_146.setText(_translate("MainWindow", "<html><head/><body><p>The polar moment of inertia<br/>of the bolt group is:<br/><span style=\" font-weight:600;\">I</span><span style=\" font-weight:600; vertical-align:sub;\">bolt =</span></p></body></html>"))
        self.label_140.setText(_translate("MainWindow", "kN"))
        self.label_148.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">F</span><span style=\" font-weight:600; vertical-align:sub;\">R</span><span style=\" font-weight:600;\">= </span>The resultant force on the<br/>most highly loaded bolt </p></body></html>"))
        self.label_145.setText(_translate("MainWindow", "mm^2"))
        self.label_147.setText(_translate("MainWindow", "kN"))
        self.label_141.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">F</span><span style=\" font-weight:600; vertical-align:sub;\">hor </span><span style=\" font-weight:600;\">=</span> The horizontal component of the force <br/>on each top and bottom bolt</p></body></html>"))
        self.label_Fr_Fvrd.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">F</span><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">r </span><span style=\" font-size:12pt; font-weight:600;\">/ F</span><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">vrd </span><span style=\" font-size:12pt; font-weight:600;\">= If &lt;1 then OK</span></p></body></html>"))
        self.label_ibolt.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">.................................................</span></p></body></html>"))
        self.label_88.setText(_translate("MainWindow", "Columns"))
        self.label_89.setText(_translate("MainWindow", "Rows:"))
        self.label_93.setText(_translate("MainWindow", "<html><head/><body><p>Number<br/>of bolts</p></body></html>"))
        self.label_90.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Partial factor for connections <br/>(not structural steel members)</span></p></body></html>"))
        self.label_91.setText(_translate("MainWindow", "<html><head/><body><p>φ<span style=\" vertical-align:sub;\">m2</span> =1.25</p></body></html>"))
        self.label_94.setText(_translate("MainWindow", "<html><head/><body><p>Full bearing resistance of opening<br/>in beam web(from bolt force)<br/><span style=\" font-weight:600;\">F</span><span style=\" font-weight:600; vertical-align:sub;\">b</span><span style=\" font-weight:600;\">=2.5*f</span><span style=\" font-weight:600; vertical-align:sub;\">u</span><span style=\" font-weight:600;\">*d*t</span><span style=\" font-weight:600; vertical-align:sub;\">w </span><span style=\" font-weight:600;\">/ φ</span><span style=\" font-weight:600; vertical-align:sub;\">m2</span></p></body></html>"))
        self.label_95.setText(_translate("MainWindow", "<html><head/><body><p>kN</p></body></html>"))
        self.label_96.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Web Splice</span></p></body></html>"))
        self.label_97.setText(_translate("MainWindow", "mm"))
        self.label_98.setText(_translate("MainWindow", "p0"))
        self.label_99.setText(_translate("MainWindow", "mm"))
        self.label_100.setText(_translate("MainWindow", "mm"))
        self.label_101.setText(_translate("MainWindow", "e2"))
        self.label_102.setText(_translate("MainWindow", "p2"))
        self.label_103.setText(_translate("MainWindow", "mm"))
        self.label_104.setText(_translate("MainWindow", "p1"))
        self.label_105.setText(_translate("MainWindow", "mm"))
        self.label_106.setText(_translate("MainWindow", "e1"))
        self.label_107.setText(_translate("MainWindow", "Vertical pitch"))
        self.label_149.setText(_translate("MainWindow", "Horizontal edge"))
        self.label_150.setText(_translate("MainWindow", "Horizontal pitch"))
        self.label_151.setText(_translate("MainWindow", "Vertical edge"))
        self.label_152.setText(_translate("MainWindow", "Distance to centreline\n"
"Height of cover plate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Web Splice"))
        self.label_112.setText(_translate("MainWindow", "<html><head/><body><p>Partial factor structural steel φ0≔</p></body></html>"))
        self.label_222.setText(_translate("MainWindow", "<html><head/><body><p>V<span style=\" vertical-align:sub;\">ed</span> / V<span style=\" vertical-align:sub;\">rd </span>= &lt;1 ?</p></body></html>"))
        self.label_110.setText(_translate("MainWindow", "kN"))
        self.label_109.setText(_translate("MainWindow", "<html><head/><body><p>Shear force V<span style=\" vertical-align:sub;\">ed</span>=</p></body></html>"))
        self.label_111.setText(_translate("MainWindow", "Resistance (for a single plate)"))
        self.lineEdit_91.setText(_translate("MainWindow", "1"))
        self.label_223.setText(_translate("MainWindow", "kN"))
        self.label_108.setText(_translate("MainWindow", "<html><head/><body><p>Cover plate web resistance to combined bending, <br/>shear and axial force</p></body></html>"))
        self.label_228.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Bending moment resistance of cover plate M</span><span style=\" font-size:10pt; vertical-align:sub;\">rd</span><span style=\" font-size:10pt;\"> = f</span><span style=\" font-size:10pt; vertical-align:sub;\">yp</span><span style=\" font-size:10pt;\"> * W</span><span style=\" font-size:10pt; vertical-align:sub;\">plp</span></p></body></html>"))
        self.label_227.setText(_translate("MainWindow", "kN*m"))
        self.label_224.setText(_translate("MainWindow", "Combined, bending moment and axial compression check"))
        self.label_225.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Modulus of cover plate (cross section taken) (t</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt;\"> * (h</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt;\">)</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">) /</span><span style=\" font-size:10pt; vertical-align:super;\"/><span style=\" font-size:10pt;\">6</span></p></body></html>"))
        self.label_226.setText(_translate("MainWindow", "mm3"))
        self.label_229.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">[ M</span><span style=\" font-size:10pt; vertical-align:sub;\">ratio</span><span style=\" font-size:10pt;\"> + M</span><span style=\" font-size:10pt; vertical-align:sub;\">add </span><span style=\" font-size:10pt;\">]</span><span style=\" font-size:10pt;\"> / M</span><span style=\" font-size:10pt; vertical-align:sub;\">rd =</span></p></body></html>"))
        self.label_230.setText(_translate("MainWindow", "---"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Calculations"))
        self.pushButton_calculate.setText(_translate("MainWindow", "Calculate !"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
