# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Marcin\PycharmProjects\kamil\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 718)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(366, 9, 457, 250))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 4, 0, 1, 3)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 0, 0, 1, 1)
        self.lineEdit_axial_force_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_axial_force_2.setEnabled(True)
        self.lineEdit_axial_force_2.setObjectName("lineEdit_axial_force_2")
        self.gridLayout_2.addWidget(self.lineEdit_axial_force_2, 2, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 0, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 1, 0, 1, 1)
        self.lineEdit_axial_force = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_axial_force.setEnabled(True)
        self.lineEdit_axial_force.setObjectName("lineEdit_axial_force")
        self.gridLayout_2.addWidget(self.lineEdit_axial_force, 1, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 1, 2, 1, 1)
        self.lineEdit_shear_force = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_shear_force.setEnabled(True)
        self.lineEdit_shear_force.setObjectName("lineEdit_shear_force")
        self.gridLayout_2.addWidget(self.lineEdit_shear_force, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 2, 0, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 2, 2, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_55.setObjectName("label_55")
        self.gridLayout_2.addWidget(self.label_55, 7, 2, 1, 1)
        self.lineEdit_ratio_bm = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_ratio_bm.setEnabled(False)
        self.lineEdit_ratio_bm.setObjectName("lineEdit_ratio_bm")
        self.gridLayout_2.addWidget(self.lineEdit_ratio_bm, 8, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_51.setObjectName("label_51")
        self.gridLayout_2.addWidget(self.label_51, 6, 0, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_57.setObjectName("label_57")
        self.gridLayout_2.addWidget(self.label_57, 9, 2, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_53.setObjectName("label_53")
        self.gridLayout_2.addWidget(self.label_53, 6, 2, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_49.setObjectName("label_49")
        self.gridLayout_2.addWidget(self.label_49, 5, 0, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_56.setObjectName("label_56")
        self.gridLayout_2.addWidget(self.label_56, 8, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_50.setObjectName("label_50")
        self.gridLayout_2.addWidget(self.label_50, 9, 0, 1, 1)
        self.lineEdit_second_moment_cover = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_second_moment_cover.setEnabled(False)
        self.lineEdit_second_moment_cover.setObjectName("lineEdit_second_moment_cover")
        self.gridLayout_2.addWidget(self.lineEdit_second_moment_cover, 7, 1, 1, 1)
        self.lineEdit_second_web_moment = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_second_web_moment.setEnabled(False)
        self.lineEdit_second_web_moment.setObjectName("lineEdit_second_web_moment")
        self.gridLayout_2.addWidget(self.lineEdit_second_web_moment, 5, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_54.setObjectName("label_54")
        self.gridLayout_2.addWidget(self.label_54, 7, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.gridLayout_2.addWidget(self.label_52, 5, 2, 1, 1)
        self.lineEdit_second_moment_single_pfc = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_second_moment_single_pfc.setEnabled(False)
        self.lineEdit_second_moment_single_pfc.setObjectName("lineEdit_second_moment_single_pfc")
        self.gridLayout_2.addWidget(self.lineEdit_second_moment_single_pfc, 6, 1, 1, 1)
        self.lineEdit_bending_moment_cover = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_bending_moment_cover.setEnabled(False)
        self.lineEdit_bending_moment_cover.setObjectName("lineEdit_bending_moment_cover")
        self.gridLayout_2.addWidget(self.lineEdit_bending_moment_cover, 9, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 351, 579))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_web_height = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_web_height.setEnabled(False)
        self.lineEdit_web_height.setObjectName("lineEdit_web_height")
        self.gridLayout.addWidget(self.lineEdit_web_height, 9, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 10, 0, 1, 1)
        self.depth_flange_fillets = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.depth_flange_fillets.setEnabled(False)
        self.depth_flange_fillets.setObjectName("depth_flange_fillets")
        self.gridLayout.addWidget(self.depth_flange_fillets, 10, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 10, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 9, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 9, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 0, 1, 1)
        self.lineEdit_web_thickness = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_web_thickness.setEnabled(False)
        self.lineEdit_web_thickness.setObjectName("lineEdit_web_thickness")
        self.gridLayout.addWidget(self.lineEdit_web_thickness, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 16, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 19, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLineWidth(1)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 17, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_37.setObjectName("label_37")
        self.gridLayout.addWidget(self.label_37, 24, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_36.setObjectName("label_36")
        self.gridLayout.addWidget(self.label_36, 17, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 18, 0, 1, 3)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout.addWidget(self.label_33, 13, 0, 1, 1)
        self.combo_steel_thickness_beam = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_steel_thickness_beam.setObjectName("combo_steel_thickness_beam")
        self.combo_steel_thickness_beam.addItem("")
        self.combo_steel_thickness_beam.addItem("")
        self.combo_steel_thickness_beam.addItem("")
        self.gridLayout.addWidget(self.combo_steel_thickness_beam, 13, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_38.setObjectName("label_38")
        self.gridLayout.addWidget(self.label_38, 25, 2, 1, 1)
        self.lineEdit_plate_yield_strength = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_plate_yield_strength.setEnabled(False)
        self.lineEdit_plate_yield_strength.setObjectName("lineEdit_plate_yield_strength")
        self.gridLayout.addWidget(self.lineEdit_plate_yield_strength, 24, 1, 1, 1)
        self.lineEdit_plate_ultimate_strength = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_plate_ultimate_strength.setEnabled(False)
        self.lineEdit_plate_ultimate_strength.setObjectName("lineEdit_plate_ultimate_strength")
        self.gridLayout.addWidget(self.lineEdit_plate_ultimate_strength, 25, 1, 1, 1)
        self.beam_yield_strength = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.beam_yield_strength.setEnabled(False)
        self.beam_yield_strength.setObjectName("beam_yield_strength")
        self.gridLayout.addWidget(self.beam_yield_strength, 16, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 21, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.gridLayout.addWidget(self.label_32, 12, 0, 1, 1)
        self.beam_ultimate_strength = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.beam_ultimate_strength.setEnabled(False)
        self.beam_ultimate_strength.setObjectName("beam_ultimate_strength")
        self.gridLayout.addWidget(self.beam_ultimate_strength, 17, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 16, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_34.setObjectName("label_34")
        self.gridLayout.addWidget(self.label_34, 13, 2, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout.addWidget(self.label_39, 21, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 20, 0, 1, 1)
        self.combo_steel_grade_plate = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_steel_grade_plate.setObjectName("combo_steel_grade_plate")
        self.combo_steel_grade_plate.addItem("")
        self.combo_steel_grade_plate.addItem("")
        self.gridLayout.addWidget(self.combo_steel_grade_plate, 20, 1, 1, 1)
        self.combo_steel_thickness_plate = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_steel_thickness_plate.setObjectName("combo_steel_thickness_plate")
        self.combo_steel_thickness_plate.addItem("")
        self.combo_steel_thickness_plate.addItem("")
        self.combo_steel_thickness_plate.addItem("")
        self.gridLayout.addWidget(self.combo_steel_thickness_plate, 21, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 8, 0, 1, 3)
        self.combo_steal_grade_beam = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_steal_grade_beam.setObjectName("combo_steal_grade_beam")
        self.combo_steal_grade_beam.addItem("")
        self.combo_steal_grade_beam.addItem("")
        self.gridLayout.addWidget(self.combo_steal_grade_beam, 12, 1, 1, 1)
        self.lineEdit_plate_thickness = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_plate_thickness.setEnabled(True)
        self.lineEdit_plate_thickness.setObjectName("lineEdit_plate_thickness")
        self.gridLayout.addWidget(self.lineEdit_plate_thickness, 22, 1, 1, 1)
        self.lineEdit_plate_depth = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_plate_depth.setEnabled(True)
        self.lineEdit_plate_depth.setObjectName("lineEdit_plate_depth")
        self.gridLayout.addWidget(self.lineEdit_plate_depth, 23, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 23, 2, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_31.setObjectName("label_31")
        self.gridLayout.addWidget(self.label_31, 22, 2, 1, 1)
        self.flange_thickness = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.flange_thickness.setEnabled(False)
        self.flange_thickness.setObjectName("flange_thickness")
        self.gridLayout.addWidget(self.flange_thickness, 5, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 7, 0, 1, 1)
        self.root_radius = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.root_radius.setEnabled(False)
        self.root_radius.setObjectName("root_radius")
        self.gridLayout.addWidget(self.root_radius, 6, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 22, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 23, 0, 1, 1)
        self.second_moment_area = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.second_moment_area.setEnabled(False)
        self.second_moment_area.setObjectName("second_moment_area")
        self.gridLayout.addWidget(self.second_moment_area, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 0, 1, 1)
        self.beam_depth = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.beam_depth.setEnabled(False)
        self.beam_depth.setObjectName("beam_depth")
        self.gridLayout.addWidget(self.beam_depth, 3, 1, 1, 1)
        self.combo_beam_size = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.combo_beam_size.setObjectName("combo_beam_size")
        self.gridLayout.addWidget(self.combo_beam_size, 2, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 11, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 24, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 25, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayout = QtWidgets.QFormLayout(self.tab_3)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.comboBox_8 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_8, 2, 1, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_48.setEnabled(False)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout_4.addWidget(self.lineEdit_48, 4, 1, 1, 1)
        self.label_113 = QtWidgets.QLabel(self.tab_3)
        self.label_113.setObjectName("label_113")
        self.gridLayout_4.addWidget(self.label_113, 3, 0, 1, 1)
        self.label_114 = QtWidgets.QLabel(self.tab_3)
        self.label_114.setObjectName("label_114")
        self.gridLayout_4.addWidget(self.label_114, 5, 0, 1, 1)
        self.label_115 = QtWidgets.QLabel(self.tab_3)
        self.label_115.setObjectName("label_115")
        self.gridLayout_4.addWidget(self.label_115, 3, 2, 1, 1)
        self.label_116 = QtWidgets.QLabel(self.tab_3)
        self.label_116.setObjectName("label_116")
        self.gridLayout_4.addWidget(self.label_116, 4, 2, 1, 1)
        self.label_117 = QtWidgets.QLabel(self.tab_3)
        self.label_117.setObjectName("label_117")
        self.gridLayout_4.addWidget(self.label_117, 5, 2, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_49.setEnabled(False)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout_4.addWidget(self.lineEdit_49, 5, 1, 1, 1)
        self.label_118 = QtWidgets.QLabel(self.tab_3)
        self.label_118.setObjectName("label_118")
        self.gridLayout_4.addWidget(self.label_118, 2, 0, 1, 1)
        self.comboBox_9 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_9, 3, 1, 1, 1)
        self.label_119 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_119.setFont(font)
        self.label_119.setObjectName("label_119")
        self.gridLayout_4.addWidget(self.label_119, 0, 0, 1, 3)
        self.label_120 = QtWidgets.QLabel(self.tab_3)
        self.label_120.setObjectName("label_120")
        self.gridLayout_4.addWidget(self.label_120, 4, 0, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.gridLayout_4)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_11.addWidget(self.line_3, 7, 0, 1, 3)
        self.label_121 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_121.setFont(font)
        self.label_121.setObjectName("label_121")
        self.gridLayout_11.addWidget(self.label_121, 6, 0, 1, 1)
        self.label_122 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_122.setFont(font)
        self.label_122.setObjectName("label_122")
        self.gridLayout_11.addWidget(self.label_122, 9, 0, 1, 1)
        self.label_123 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_123.setFont(font)
        self.label_123.setObjectName("label_123")
        self.gridLayout_11.addWidget(self.label_123, 1, 0, 1, 1)
        self.label_124 = QtWidgets.QLabel(self.tab_3)
        self.label_124.setObjectName("label_124")
        self.gridLayout_11.addWidget(self.label_124, 1, 2, 1, 1)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_50.setEnabled(False)
        self.lineEdit_50.setMaxLength(3)
        self.lineEdit_50.setFrame(True)
        self.lineEdit_50.setClearButtonEnabled(False)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout_11.addWidget(self.lineEdit_50, 1, 1, 1, 1)
        self.label_125 = QtWidgets.QLabel(self.tab_3)
        self.label_125.setObjectName("label_125")
        self.gridLayout_11.addWidget(self.label_125, 9, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 8, 0, 1, 1)
        self.label_126 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_126.setFont(font)
        self.label_126.setObjectName("label_126")
        self.gridLayout_11.addWidget(self.label_126, 5, 0, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_51.setEnabled(False)
        self.lineEdit_51.setMaxLength(3)
        self.lineEdit_51.setFrame(True)
        self.lineEdit_51.setClearButtonEnabled(False)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout_11.addWidget(self.lineEdit_51, 6, 1, 1, 1)
        self.label_127 = QtWidgets.QLabel(self.tab_3)
        self.label_127.setObjectName("label_127")
        self.gridLayout_11.addWidget(self.label_127, 6, 2, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_52.setEnabled(False)
        self.lineEdit_52.setMaxLength(3)
        self.lineEdit_52.setFrame(True)
        self.lineEdit_52.setClearButtonEnabled(False)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout_11.addWidget(self.lineEdit_52, 13, 1, 1, 2)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_53.setEnabled(False)
        self.lineEdit_53.setMaxLength(3)
        self.lineEdit_53.setFrame(True)
        self.lineEdit_53.setClearButtonEnabled(False)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout_11.addWidget(self.lineEdit_53, 5, 1, 1, 1)
        self.label_128 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_128.setFont(font)
        self.label_128.setObjectName("label_128")
        self.gridLayout_11.addWidget(self.label_128, 3, 0, 1, 1)
        self.label_129 = QtWidgets.QLabel(self.tab_3)
        self.label_129.setObjectName("label_129")
        self.gridLayout_11.addWidget(self.label_129, 5, 2, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_54.setEnabled(False)
        self.lineEdit_54.setMaxLength(3)
        self.lineEdit_54.setFrame(True)
        self.lineEdit_54.setClearButtonEnabled(False)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout_11.addWidget(self.lineEdit_54, 9, 1, 1, 1)
        self.label_130 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_130.setFont(font)
        self.label_130.setObjectName("label_130")
        self.gridLayout_11.addWidget(self.label_130, 2, 0, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_55.setEnabled(False)
        self.lineEdit_55.setMaxLength(3)
        self.lineEdit_55.setFrame(True)
        self.lineEdit_55.setClearButtonEnabled(False)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout_11.addWidget(self.lineEdit_55, 3, 1, 1, 1)
        self.label_131 = QtWidgets.QLabel(self.tab_3)
        self.label_131.setObjectName("label_131")
        self.gridLayout_11.addWidget(self.label_131, 2, 2, 1, 1)
        self.label_132 = QtWidgets.QLabel(self.tab_3)
        self.label_132.setObjectName("label_132")
        self.gridLayout_11.addWidget(self.label_132, 3, 2, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_56.setEnabled(False)
        self.lineEdit_56.setMaxLength(3)
        self.lineEdit_56.setFrame(True)
        self.lineEdit_56.setClearButtonEnabled(False)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout_11.addWidget(self.lineEdit_56, 2, 1, 1, 1)
        self.label_133 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_133.setFont(font)
        self.label_133.setObjectName("label_133")
        self.gridLayout_11.addWidget(self.label_133, 12, 0, 1, 1)
        self.label_134 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_134.setFont(font)
        self.label_134.setObjectName("label_134")
        self.gridLayout_11.addWidget(self.label_134, 11, 0, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_57.setEnabled(False)
        self.lineEdit_57.setMaxLength(3)
        self.lineEdit_57.setFrame(True)
        self.lineEdit_57.setClearButtonEnabled(False)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout_11.addWidget(self.lineEdit_57, 10, 1, 1, 1)
        self.label_135 = QtWidgets.QLabel(self.tab_3)
        self.label_135.setObjectName("label_135")
        self.gridLayout_11.addWidget(self.label_135, 10, 2, 1, 1)
        self.label_136 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_136.setFont(font)
        self.label_136.setObjectName("label_136")
        self.gridLayout_11.addWidget(self.label_136, 13, 0, 1, 1)
        self.label_137 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_137.setFont(font)
        self.label_137.setObjectName("label_137")
        self.gridLayout_11.addWidget(self.label_137, 10, 0, 1, 1)
        self.lineEdit_58 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_58.setEnabled(False)
        self.lineEdit_58.setMaxLength(3)
        self.lineEdit_58.setFrame(True)
        self.lineEdit_58.setClearButtonEnabled(False)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.gridLayout_11.addWidget(self.lineEdit_58, 12, 1, 1, 1)
        self.label_138 = QtWidgets.QLabel(self.tab_3)
        self.label_138.setObjectName("label_138")
        self.gridLayout_11.addWidget(self.label_138, 11, 2, 1, 1)
        self.lineEdit_59 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_59.setEnabled(False)
        self.lineEdit_59.setMaxLength(3)
        self.lineEdit_59.setFrame(True)
        self.lineEdit_59.setClearButtonEnabled(False)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.gridLayout_11.addWidget(self.lineEdit_59, 11, 1, 1, 1)
        self.label_139 = QtWidgets.QLabel(self.tab_3)
        self.label_139.setObjectName("label_139")
        self.gridLayout_11.addWidget(self.label_139, 12, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_11.addWidget(self.label_4, 0, 0, 1, 1)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.gridLayout_11)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 351, 111))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_68 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_68.setObjectName("label_68")
        self.gridLayout_6.addWidget(self.label_68, 1, 0, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.gridLayout_6.addWidget(self.label_67, 1, 1, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.gridLayout_6.addWidget(self.label_69, 2, 0, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.lineEdit_30.setEnabled(False)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_6.addWidget(self.lineEdit_30, 2, 1, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setObjectName("label_71")
        self.gridLayout_6.addWidget(self.label_71, 2, 2, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_66.setObjectName("label_66")
        self.gridLayout_6.addWidget(self.label_66, 0, 0, 1, 3)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 130, 233, 138))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_81 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.gridLayout_7.addWidget(self.label_81, 3, 4, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_75.setFont(font)
        self.label_75.setObjectName("label_75")
        self.gridLayout_7.addWidget(self.label_75, 4, 2, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.gridLayout_7.addWidget(self.label_80, 2, 4, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.gridLayout_7.addWidget(self.label_79, 1, 4, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_34.setEnabled(True)
        self.lineEdit_34.setMaxLength(3)
        self.lineEdit_34.setFrame(True)
        self.lineEdit_34.setClearButtonEnabled(False)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_7.addWidget(self.lineEdit_34, 3, 3, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_33.setEnabled(True)
        self.lineEdit_33.setMaxLength(3)
        self.lineEdit_33.setFrame(True)
        self.lineEdit_33.setClearButtonEnabled(False)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_7.addWidget(self.lineEdit_33, 2, 3, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_35.setEnabled(True)
        self.lineEdit_35.setMaxLength(3)
        self.lineEdit_35.setFrame(True)
        self.lineEdit_35.setClearButtonEnabled(False)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_7.addWidget(self.lineEdit_35, 4, 3, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_32.setEnabled(True)
        self.lineEdit_32.setMaxLength(3)
        self.lineEdit_32.setFrame(True)
        self.lineEdit_32.setClearButtonEnabled(False)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_7.addWidget(self.lineEdit_32, 1, 3, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.gridLayout_7.addWidget(self.label_78, 2, 2, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_77.setFont(font)
        self.label_77.setObjectName("label_77")
        self.gridLayout_7.addWidget(self.label_77, 3, 2, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.gridLayout_7.addWidget(self.label_82, 4, 4, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setObjectName("label_76")
        self.gridLayout_7.addWidget(self.label_76, 1, 2, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        self.lineEdit_31.setEnabled(True)
        self.lineEdit_31.setMaxLength(3)
        self.lineEdit_31.setFrame(True)
        self.lineEdit_31.setClearButtonEnabled(False)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_7.addWidget(self.lineEdit_31, 0, 3, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.gridLayout_7.addWidget(self.label_70, 0, 4, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setObjectName("label_74")
        self.gridLayout_7.addWidget(self.label_74, 0, 2, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.gridLayout_7.addWidget(self.label_83, 3, 1, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.gridLayout_7.addWidget(self.label_84, 0, 1, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.gridLayout_7.addWidget(self.label_85, 1, 1, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_86.setFont(font)
        self.label_86.setObjectName("label_86")
        self.gridLayout_7.addWidget(self.label_86, 2, 1, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_87.setFont(font)
        self.label_87.setObjectName("label_87")
        self.gridLayout_7.addWidget(self.label_87, 4, 1, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(250, 130, 111, 86))
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.spinBox_columns = QtWidgets.QSpinBox(self.gridLayoutWidget_8)
        self.spinBox_columns.setMinimum(2)
        self.spinBox_columns.setMaximum(10)
        self.spinBox_columns.setObjectName("spinBox_columns")
        self.gridLayout_10.addWidget(self.spinBox_columns, 0, 1, 1, 1)
        self.spinBox_rows = QtWidgets.QSpinBox(self.gridLayoutWidget_8)
        self.spinBox_rows.setMinimum(2)
        self.spinBox_rows.setMaximum(10)
        self.spinBox_rows.setObjectName("spinBox_rows")
        self.gridLayout_10.addWidget(self.spinBox_rows, 1, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_72.setFont(font)
        self.label_72.setObjectName("label_72")
        self.gridLayout_10.addWidget(self.label_72, 0, 0, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.gridLayout_10.addWidget(self.label_73, 1, 0, 1, 1)
        self.label_92 = QtWidgets.QLabel(self.gridLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_92.setFont(font)
        self.label_92.setObjectName("label_92")
        self.gridLayout_10.addWidget(self.label_92, 2, 0, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.gridLayoutWidget_8)
        self.lineEdit_38.setEnabled(False)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_10.addWidget(self.lineEdit_38, 2, 1, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(480, 280, 341, 138))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_112 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_112.setFont(font)
        self.label_112.setObjectName("label_112")
        self.gridLayout_8.addWidget(self.label_112, 2, 0, 1, 1)
        self.label_222 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_222.setFont(font)
        self.label_222.setObjectName("label_222")
        self.gridLayout_8.addWidget(self.label_222, 4, 0, 1, 1)
        self.label_110 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_110.setObjectName("label_110")
        self.gridLayout_8.addWidget(self.label_110, 1, 2, 1, 1)
        self.label_109 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_109.setFont(font)
        self.label_109.setObjectName("label_109")
        self.gridLayout_8.addWidget(self.label_109, 1, 0, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_47.setEnabled(False)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_8.addWidget(self.lineEdit_47, 1, 1, 1, 1)
        self.label_111 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_111.setFont(font)
        self.label_111.setObjectName("label_111")
        self.gridLayout_8.addWidget(self.label_111, 3, 0, 1, 1)
        self.lineEdit_89 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_89.setEnabled(False)
        self.lineEdit_89.setObjectName("lineEdit_89")
        self.gridLayout_8.addWidget(self.lineEdit_89, 4, 1, 1, 1)
        self.lineEdit_90 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_90.setEnabled(False)
        self.lineEdit_90.setObjectName("lineEdit_90")
        self.gridLayout_8.addWidget(self.lineEdit_90, 3, 1, 1, 1)
        self.lineEdit_91 = QtWidgets.QLineEdit(self.gridLayoutWidget_6)
        self.lineEdit_91.setEnabled(True)
        self.lineEdit_91.setObjectName("lineEdit_91")
        self.gridLayout_8.addWidget(self.lineEdit_91, 2, 1, 1, 1)
        self.label_223 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.label_223.setObjectName("label_223")
        self.gridLayout_8.addWidget(self.label_223, 3, 2, 1, 1)
        self.label_108 = QtWidgets.QLabel(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_108.setFont(font)
        self.label_108.setObjectName("label_108")
        self.gridLayout_8.addWidget(self.label_108, 0, 0, 1, 3)
        self.gridLayoutWidget_17 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_17.setGeometry(QtCore.QRect(10, 280, 458, 96))
        self.gridLayoutWidget_17.setObjectName("gridLayoutWidget_17")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.gridLayoutWidget_17)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_228 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_228.setObjectName("label_228")
        self.gridLayout_19.addWidget(self.label_228, 3, 0, 1, 1)
        self.label_227 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_227.setObjectName("label_227")
        self.gridLayout_19.addWidget(self.label_227, 3, 2, 1, 1)
        self.lineEdit_93 = QtWidgets.QLineEdit(self.gridLayoutWidget_17)
        self.lineEdit_93.setEnabled(False)
        self.lineEdit_93.setObjectName("lineEdit_93")
        self.gridLayout_19.addWidget(self.lineEdit_93, 3, 1, 1, 1)
        self.lineEdit_92 = QtWidgets.QLineEdit(self.gridLayoutWidget_17)
        self.lineEdit_92.setEnabled(False)
        self.lineEdit_92.setObjectName("lineEdit_92")
        self.gridLayout_19.addWidget(self.lineEdit_92, 2, 1, 1, 1)
        self.label_224 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_224.setFont(font)
        self.label_224.setObjectName("label_224")
        self.gridLayout_19.addWidget(self.label_224, 1, 0, 1, 1)
        self.label_225 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_225.setObjectName("label_225")
        self.gridLayout_19.addWidget(self.label_225, 2, 0, 1, 1)
        self.label_226 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_226.setObjectName("label_226")
        self.gridLayout_19.addWidget(self.label_226, 2, 2, 1, 1)
        self.label_229 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_229.setObjectName("label_229")
        self.gridLayout_19.addWidget(self.label_229, 4, 0, 1, 1)
        self.lineEdit_94 = QtWidgets.QLineEdit(self.gridLayoutWidget_17)
        self.lineEdit_94.setEnabled(False)
        self.lineEdit_94.setObjectName("lineEdit_94")
        self.gridLayout_19.addWidget(self.lineEdit_94, 4, 1, 1, 1)
        self.label_230 = QtWidgets.QLabel(self.gridLayoutWidget_17)
        self.label_230.setObjectName("label_230")
        self.gridLayout_19.addWidget(self.label_230, 4, 2, 1, 1)
        self.label_diagram = QtWidgets.QLabel(self.tab_2)
        self.label_diagram.setGeometry(QtCore.QRect(370, 10, 461, 261))
        self.label_diagram.setAutoFillBackground(False)
        self.label_diagram.setText("")
        self.label_diagram.setPixmap(QtGui.QPixmap("C:\\Users\\Marcin\\PycharmProjects\\kamil\\media/2x2.jpeg"))
        self.label_diagram.setScaledContents(True)
        self.label_diagram.setObjectName("label_diagram")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.pushButton_calculate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_calculate.setObjectName("pushButton_calculate")
        self.verticalLayout.addWidget(self.pushButton_calculate)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 865, 21))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Value of moment transferred to splice cover plate</span></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Design Shear Force V</span><span style=\" font-size:10pt; vertical-align:sub;\">ed</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">kN</span></p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Design Axial Force M</span><span style=\" font-size:10pt; vertical-align:sub;\">ed</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">kN*m</span></p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Design Bending Force N</span><span style=\" font-size:10pt; vertical-align:sub;\">ed</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_47.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">kN</span></p></body></html>"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">cm</span><span style=\" font-size:10pt; vertical-align:super;\">4</span></p></body></html>"))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Second moment of single PFC I</span><span style=\" font-size:10pt; vertical-align:sub;\">xx</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_57.setText(_translate("MainWindow", "<html><head/><body><p>m*kN</p></body></html>"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">cm</span><span style=\" font-size:10pt; vertical-align:super;\">4</span></p></body></html>"))
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Second moment of web I</span><span style=\" font-size:10pt; vertical-align:sub;\">web</span><span style=\" font-size:10pt;\">= (t</span><span style=\" font-size:10pt; vertical-align:sub;\">w</span><span style=\" font-size:10pt;\">h</span><span style=\" font-size:10pt; vertical-align:sub;\">w</span><span style=\" font-size:10pt; vertical-align:super;\">3</span><span style=\" font-size:10pt;\">) / 12=</span></p></body></html>"))
        self.label_56.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Ratio of moment carried by cover plate<br/>Ratio</span><span style=\" font-size:10pt; vertical-align:sub;\">BM</span><span style=\" font-size:10pt;\">= I</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt;\">/I</span><span style=\" font-size:10pt; vertical-align:sub;\">xx </span></p></body></html>"))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Bending moment carried by cover plate<br/>M</span><span style=\" font-size:10pt; vertical-align:sub;\">ratio</span><span style=\" font-size:10pt;\"> = M</span><span style=\" font-size:10pt; vertical-align:sub;\">ed</span><span style=\" font-size:10pt;\"> * Ratio</span><span style=\" font-size:10pt; vertical-align:sub;\">BM</span><span style=\" font-size:10pt;\"> = </span></p></body></html>"))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Second moment of cover plate I</span><span style=\" font-size:10pt; vertical-align:sub;\">p </span><span style=\" font-size:10pt;\">= (t</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt;\">*h</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt; vertical-align:super;\">3</span><span style=\" font-size:10pt;\">) / 12 =</span></p></body></html>"))
        self.label_52.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">cm</span><span style=\" font-size:10pt; vertical-align:super;\">4</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Depth between flange fillets<br/>d</span><span style=\" font-size:10pt; vertical-align:sub;\">b</span><span style=\" font-size:10pt;\"> = h -2(t</span><span style=\" font-size:10pt; vertical-align:sub;\">f</span><span style=\" font-size:10pt;\">+r)=</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "mm"))
        self.label_21.setText(_translate("MainWindow", "mm"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Web height <br/>h</span><span style=\" font-size:10pt; vertical-align:sub;\">w</span><span style=\" font-size:10pt;\">=h -2t</span><span style=\" font-size:10pt; vertical-align:sub;\">f</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Web Thickness <span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">w</span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Yield Strength f</span><span style=\" font-size:10pt; vertical-align:sub;\">y</span><span style=\" font-size:10pt;\"> =</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "Cover Plate Geometry"))
        self.label_9.setText(_translate("MainWindow", "Beam Geometry "))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Ultimate Strength f</span><span style=\" font-size:10pt; vertical-align:sub;\">u</span><span style=\" font-size:10pt;\"> =</span></p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "N/mm^2"))
        self.label_36.setText(_translate("MainWindow", "N/mm^2"))
        self.label_33.setText(_translate("MainWindow", "Steel Thickness <= (mm)"))
        self.combo_steel_thickness_beam.setItemText(0, _translate("MainWindow", "16"))
        self.combo_steel_thickness_beam.setItemText(1, _translate("MainWindow", "40"))
        self.combo_steel_thickness_beam.setItemText(2, _translate("MainWindow", "63"))
        self.label_38.setText(_translate("MainWindow", "N/mm^2"))
        self.label_41.setText(_translate("MainWindow", "mm"))
        self.label_32.setText(_translate("MainWindow", "Steel Grade"))
        self.label_35.setText(_translate("MainWindow", "N/mm^2"))
        self.label_34.setText(_translate("MainWindow", "mm"))
        self.label_39.setText(_translate("MainWindow", "Steel Thickness <= (mm)"))
        self.label_40.setText(_translate("MainWindow", "Steel Grade"))
        self.combo_steel_grade_plate.setItemText(0, _translate("MainWindow", "S275"))
        self.combo_steel_grade_plate.setItemText(1, _translate("MainWindow", "S355"))
        self.combo_steel_thickness_plate.setItemText(0, _translate("MainWindow", "16"))
        self.combo_steel_thickness_plate.setItemText(1, _translate("MainWindow", "40"))
        self.combo_steel_thickness_plate.setItemText(2, _translate("MainWindow", "63"))
        self.combo_steal_grade_beam.setItemText(0, _translate("MainWindow", "S275"))
        self.combo_steal_grade_beam.setItemText(1, _translate("MainWindow", "S355"))
        self.label_17.setText(_translate("MainWindow", "mm"))
        self.label_16.setText(_translate("MainWindow", "mm"))
        self.label_30.setText(_translate("MainWindow", "mm"))
        self.label_31.setText(_translate("MainWindow", "mm"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Second moment of area I<span style=\" vertical-align:sub;\">xx</span>=</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Flange Thickness <span style=\" font-weight:600;\">t</span><span style=\" font-weight:600; vertical-align:sub;\">f</span><span style=\" font-weight:600;\">=</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "Root radius r="))
        self.label_13.setText(_translate("MainWindow", "mm"))
        self.label_28.setText(_translate("MainWindow", "Cover Plate Thickness tp ="))
        self.label_29.setText(_translate("MainWindow", "Cover Plate Depth hp="))
        self.label_11.setText(_translate("MainWindow", "mm"))
        self.label_20.setText(_translate("MainWindow", "mm"))
        self.label_10.setText(_translate("MainWindow", "Beam depth h="))
        self.label_18.setText(_translate("MainWindow", "Beam Size:"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Yield Strength f</span><span style=\" font-size:10pt; vertical-align:sub;\">yp</span><span style=\" font-size:10pt;\"> =</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Ultimate Strength f</span><span style=\" font-size:10pt; vertical-align:sub;\">up</span><span style=\" font-size:10pt;\"> =</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Beam Geometry and Cover Plate"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "8.8"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "4.6"))
        self.label_113.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Bolt shank diameter d=</span></p></body></html>"))
        self.label_114.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Single Shear force resistance (ULS) F</span><span style=\" font-size:10pt; vertical-align:sub;\">vrd</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_115.setText(_translate("MainWindow", "mm"))
        self.label_116.setText(_translate("MainWindow", "mm"))
        self.label_117.setText(_translate("MainWindow", "kN"))
        self.label_118.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Class</span></p></body></html>"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "12"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "16"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "20"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "24"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "30"))
        self.label_119.setText(_translate("MainWindow", "Bolts"))
        self.label_120.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Hole opening diamter d</span><span style=\" font-size:10pt; vertical-align:sub;\">o</span><span style=\" font-size:10pt;\">=</span></p></body></html>"))
        self.label_121.setText(_translate("MainWindow", "<html><head/><body><p>M<span style=\" vertical-align:sub;\">add</span>=V<span style=\" vertical-align:sub;\">ed</span>*<span style=\" vertical-align:sub;\"/>(p0+ [ p1*(col -1) ] / 2)</p></body></html>"))
        self.label_122.setText(_translate("MainWindow", "<html><head/><body><p>The polar moment of inertia<br/>of the bolt group is:<br/>I<span style=\" vertical-align:sub;\">bolt =</span></p></body></html>"))
        self.label_123.setText(_translate("MainWindow", "<html><head/><body><p>M<span style=\" vertical-align:sub;\">ratio</span>=</p></body></html>"))
        self.label_124.setText(_translate("MainWindow", "kN*m"))
        self.label_125.setText(_translate("MainWindow", "mm^2"))
        self.label_126.setText(_translate("MainWindow", "<html><head/><body><p>Force per bolt due to axial compression <br/>F<span style=\" vertical-align:sub;\">Ned</span>= N<span style=\" vertical-align:sub;\">ratio</span> / n</p></body></html>"))
        self.label_127.setText(_translate("MainWindow", "kN*m"))
        self.label_128.setText(_translate("MainWindow", "<html><head/><body><p>Force per bolt due to vertical shear <br/>F<span style=\" vertical-align:sub;\">Ved</span>= V<span style=\" vertical-align:sub;\">ed </span>/ n</p></body></html>"))
        self.label_129.setText(_translate("MainWindow", "kN"))
        self.label_130.setText(_translate("MainWindow", "<html><head/><body><p>N<span style=\" vertical-align:sub;\">ratio</span>=</p></body></html>"))
        self.label_131.setText(_translate("MainWindow", "kN"))
        self.label_132.setText(_translate("MainWindow", "kN"))
        self.label_133.setText(_translate("MainWindow", "<html><head/><body><p>The resultant force on the<br/> most highly loaded bolt </p></body></html>"))
        self.label_134.setText(_translate("MainWindow", "<html><head/><body><p>The Vertical component of the force<br/>on each top and bottom bolt</p></body></html>"))
        self.label_135.setText(_translate("MainWindow", "kN"))
        self.label_136.setText(_translate("MainWindow", "<html><head/><body><p>F<span style=\" vertical-align:sub;\">r </span>/ F<span style=\" vertical-align:sub;\">vrd </span>=   If &lt;1 then OK</p></body></html>"))
        self.label_137.setText(_translate("MainWindow", "<html><head/><body><p>The horizontal component of the force <br/>on each top and bottom bolt</p></body></html>"))
        self.label_138.setText(_translate("MainWindow", "kN"))
        self.label_139.setText(_translate("MainWindow", "kN"))
        self.label_4.setText(_translate("MainWindow", "Bolt forces at ULS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Bolts and Forces"))
        self.label_68.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Partial factor for connections <br/>(not structural steel members)</span></p></body></html>"))
        self.label_67.setText(_translate("MainWindow", "<html><head/><body><p>φ<span style=\" vertical-align:sub;\">m2</span> =1.25</p></body></html>"))
        self.label_69.setText(_translate("MainWindow", "<html><head/><body><p>Full bearing resistance of opening<br/>in beam web(from bolt force)<br/>F<span style=\" vertical-align:sub;\">b</span>=2.5*f<span style=\" vertical-align:sub;\">u</span>*d*t<span style=\" vertical-align:sub;\">w </span>/ φ<span style=\" vertical-align:sub;\">m2</span></p></body></html>"))
        self.label_71.setText(_translate("MainWindow", "<html><head/><body><p>kN</p></body></html>"))
        self.label_66.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Web Splice</span></p></body></html>"))
        self.label_81.setText(_translate("MainWindow", "mm"))
        self.label_75.setText(_translate("MainWindow", "p0"))
        self.label_80.setText(_translate("MainWindow", "mm"))
        self.label_79.setText(_translate("MainWindow", "mm"))
        self.label_78.setText(_translate("MainWindow", "e2"))
        self.label_77.setText(_translate("MainWindow", "p2"))
        self.label_82.setText(_translate("MainWindow", "mm"))
        self.label_76.setText(_translate("MainWindow", "p1"))
        self.label_70.setText(_translate("MainWindow", "mm"))
        self.label_74.setText(_translate("MainWindow", "e1"))
        self.label_83.setText(_translate("MainWindow", "Vertical pitch"))
        self.label_84.setText(_translate("MainWindow", "Horizontal edge"))
        self.label_85.setText(_translate("MainWindow", "Horizontal pitch"))
        self.label_86.setText(_translate("MainWindow", "Vertical edge"))
        self.label_87.setText(_translate("MainWindow", "Distance to centreline\n"
"Height of cover plate"))
        self.label_72.setText(_translate("MainWindow", "Columns"))
        self.label_73.setText(_translate("MainWindow", "Rows:"))
        self.label_92.setText(_translate("MainWindow", "<html><head/><body><p>Number<br/>of bolts</p></body></html>"))
        self.label_112.setText(_translate("MainWindow", "<html><head/><body><p>Partial factor structural steel φ0≔</p></body></html>"))
        self.label_222.setText(_translate("MainWindow", "<html><head/><body><p>V<span style=\" vertical-align:sub;\">ed</span> / V<span style=\" vertical-align:sub;\">rd </span>= &lt;1 ?</p></body></html>"))
        self.label_110.setText(_translate("MainWindow", "kN"))
        self.label_109.setText(_translate("MainWindow", "<html><head/><body><p>Shear force V<span style=\" vertical-align:sub;\">ed</span>=</p></body></html>"))
        self.label_111.setText(_translate("MainWindow", "Resistance (for a single plate)"))
        self.lineEdit_91.setText(_translate("MainWindow", "1"))
        self.label_223.setText(_translate("MainWindow", "kN"))
        self.label_108.setText(_translate("MainWindow", "<html><head/><body><p>Cover plate web resistance to combined bending, <br/>shear and axial force</p></body></html>"))
        self.label_228.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Bending moment resistance of cover plate M</span><span style=\" font-size:10pt; vertical-align:sub;\">rd</span><span style=\" font-size:10pt;\"> = f</span><span style=\" font-size:10pt; vertical-align:sub;\">yp</span><span style=\" font-size:10pt;\"> * W</span><span style=\" font-size:10pt; vertical-align:sub;\">plp</span></p></body></html>"))
        self.label_227.setText(_translate("MainWindow", "kN*m"))
        self.label_224.setText(_translate("MainWindow", "Combined, bending moment and axial compression check"))
        self.label_225.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Modulus of cover plate (cross section taken) (t</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt;\"> * (h</span><span style=\" font-size:10pt; vertical-align:sub;\">p</span><span style=\" font-size:10pt;\">)</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">) /</span><span style=\" font-size:10pt; vertical-align:super;\"/><span style=\" font-size:10pt;\">6</span></p></body></html>"))
        self.label_226.setText(_translate("MainWindow", "mm3"))
        self.label_229.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">[ M</span><span style=\" font-size:10pt; vertical-align:sub;\">ratio</span><span style=\" font-size:10pt;\"> + M</span><span style=\" font-size:10pt; vertical-align:sub;\">add </span><span style=\" font-size:10pt;\">]</span><span style=\" font-size:10pt;\"> / M</span><span style=\" font-size:10pt; vertical-align:sub;\">rd =</span></p></body></html>"))
        self.label_230.setText(_translate("MainWindow", "---"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Bolts and Web Splice"))
        self.pushButton_calculate.setText(_translate("MainWindow", "Calculate !"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
